#!/bin/bash
# Move to the directory of the script to ensure file paths are appropriate
cd "$(dirname "$0")"

# silent install or request confirmation
if [ "$1" == "-q" ]
then
	agree="y"
else
	while [ "$agree" != "y" ] && [ "$agree" != "n" ]
	do
		read -p "are you sure you want to install dot-files? (y|n): " agree
	done
fi

# install the files
if [ "$agree" = "y" ]
then
	cp -aR ./src/. ~/
fi

read -p "Enter your name for GIT (enter to skip): " gitname
read -p "Enter your email for GIT (enter to skip): " gitemail

if [[ ! -z "${gitname// }" ]]
then
	git config --global user.name "$gitname"
fi
if [[ ! -z "${gitemail// }" ]]
then
	git config --global user.email "$gitemail"
fi

exit 0
